### ISSUE TITLE
Won't load

### ISSUE THREAD

**Issue by Ylacat** [Ylacat/applegod#1]
[15:28:13] [Server thread/WARN]: Plugin AppleGOD v0.0.2 does not specify an api-version.
[15:28:13] [Server thread/ERROR]: Could not load 'plugins\AppleGOD-0.0.2.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `com.tacaly.AppleGOD'
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:61) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:333) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:252) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:347) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:194) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:761) [spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.ClassNotFoundException: com.tacaly.AppleGOD
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_211]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_211]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_211]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:59) ~[spigot-1.14.2.jar:git-Spigot-093165d-ba575a5]

**Comment by Ylacat** [comment]
Fixed in 0.0.3
