### ISSUE TITLE
APPLEGOD-R - IllegalStateException

### ISSUE THREAD

**Issue by Ylacat** [Ylacat/AppleGod#13]
ID: c9b586d0e8224d75bad0e142380580d1
July 14, 2021, 12:56:39 p.m. UTC

IllegalStateException: TimeSkipEvent cannot be triggered asynchronously from another thread.
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:572)
    at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.setFullTime(CraftWorld.java:821)
    at org.bukkit.craftbukkit.v1_17_R1.CraftWorld.setTime(CraftWorld.java:809)
    at io.github.toydotgame.SinglePlayerSleep.SinglePlayerSleep$1.run(SinglePlayerSleep.java:23)

**Comment by Ylacat** [comment]
AppleGOD won't support "SimplePluginManager"
